# Generated by Django 4.2.3 on 2023-07-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('vote_average', models.CharField(max_length=20)),
                ('vote_count', models.CharField(max_length=20)),
                ('release_date', models.DateField()),
                ('overview', models.TextField()),
                ('popularity', models.CharField(max_length=30)),
                ('poster_path', models.ImageField(upload_to='movie')),
            ],
        ),
    ]
